name: CI/CD for React Movie Ticket App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'  # Cấu hình cache cho pnpm

      - name: Enable corepack
        run: corepack enable  # Kích hoạt corepack

      - name: Install pnpm
        run: corepack prepare pnpm@latest --activate  # Cài và kích hoạt pnpm

      - name: Verify pnpm installation
        run: pnpm --version  # Kiểm tra phiên bản pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build application
        run: pnpm run build

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Enable corepack
        run: corepack enable

      - name: Install pnpm
        run: corepack prepare pnpm@latest --activate

      - name: Verify pnpm installation
        run: pnpm --version

      - name: Install dependencies
        run: pnpm install

      - name: Build application
        run: pnpm run build

      - name: Deploy to EC2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_DEST_PATH: ${{ secrets.EC2_DEST_PATH_APP }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key
          chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key $EC2_USER@$EC2_HOST << 'EOF'
            cd $EC2_DEST_PATH
            git pull origin main
            pnpm install
            pnpm run build
            sudo systemctl restart nginx
          EOF
          rm private_key